### ISSUE TITLE
Sharing goes to the wrong URL

### ISSUE THREAD

**Issue by EngstromJimmy** [Swetugg/swetugg-public#23]
If you look at a speaker and press the tweet button, the suggested tweet has the wrong domain.

Example:
Don't miss "Introduction to Serverless with .NET + AWS Lambda" with @TheCodeTraveler at @Swetugg Göteborg 2023! https://swetuggv2.azurewebsites.net/gbg-2023/speakers/brandon-minnick#introduction-to-serverless-with-net-aws-lambda

**Comment by ceciliasharp** [comment]
New speaker page coming out today will not have any share tweetbutton, the old once seams to not have been used at all.
